# Generated by Django 2.1.7 on 2019-04-08 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 18, 15, 11, 734442), verbose_name='published'),
        ),
    ]
