# Generated by Django 2.1.7 on 2019-04-08 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilapp', '0002_auto_20190408_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 18, 30, 6, 257400), verbose_name='published'),
        ),
    ]
